routes/web.php
<?php

Route::get('encrypts',function(){
    dd(bcrypt('admin'));
});

//Clear configurations:
            Route::get('/config-clear', function() {
                $status = Artisan::call('config:clear');
                return '<h1>Configurations cleared</h1>';
            });

//Clear cache:
            Route::get('/cache-clear', function() {
                $status = Artisan::call('cache:clear');
                return '<h1>Cache cleared</h1>';
            });

//Clear configuration cache:
            Route::get('/config-cache', function() {
                $status = Artisan::call('config:cache');
                return '<h1>Configurations cache cleared</h1>';
            });
    Route::get('/reset', function(){
        \Artisan::call('migrate:refresh',['--seed' => ' ']);
    });
/*
|--------------------------------------------------------------------------
| Auth routes
|--------------------------------------------------------------------------
 */

//Authentication routes
Route::auth();
Route::get('logout', 'Auth\LoginController@logout');
Route::get('password/reset/{token}/{email}', 'Auth\ResetPasswordController@showResetForm');

//OAuth2 routes
Route::get('auth/facebook', 'OAuth\FacebookController@login');
Route::get('auth/facebook/callback', "OAuth\FacebookController@callback");

Route::get('auth/twitter', 'OAuth\TwitterController@login');
Route::get('auth/twitter/callback', "OAuth\TwitterController@callback");

Route::get('auth/google', 'OAuth\GoogleController@login');
Route::get('auth/google/callback', "OAuth\GoogleController@callback");
Route::post('upload_avatar/{id}','Backend\AvatarController@update_avatar');
/*
|--------------------------------------------------------------------------
| Front-end routes
|--------------------------------------------------------------------------
 */

Route::get("/", ['as' => 'home', 'uses' => 'Frontend\ArticleController@index']);

Route::get("sitemap", ['as' => 'frontend.sitemap', 'uses' => 'Frontend\HomepageController@sitemap']);
Route::get("terms-and-conditions", ['as' => 'frontend.terms-and-conditions', 'uses' => 'Frontend\HomepageController@termsAndConditions']);
Route::get("privacy-policy", ['as' => 'frontend.privacy-policy', 'uses' => 'Frontend\HomepageController@privacyPolicy']);

Route::post('subscribe', 'Frontend\HomepageController@subscribe');
Route::get('subscription/confirm/{email}', ['as' => 'frontend.subscription', 'uses' => 'Frontend\HomepageController@subscriptionConfirm']);

Route::get("categories", ['as' => 'frontend.categories', 'uses' => 'Frontend\CategoryController@index']);
Route::get("categories/{slug}", ['as' => 'frontend.categories.show', 'uses' => 'Frontend\CategoryController@show'])->where('slug', '[\w\d\-\_]+');

Route::get("tags", ['as' => 'frontend.tags', 'uses' => 'Frontend\TagController@index']);
Route::get("tags/{slug}", ['as' => 'frontend.tags.show', 'uses' => 'Frontend\TagController@show'])->where('slug', '[\w\d\-\_]+');

Route::post('contact', 'Frontend\HomepageController@contact');
Route::get('about', ['as' => 'frontend.about', 'uses' => 'Frontend\HomepageController@about']);
Route::get('about/{slug}', ['as' => 'frontend.about.author', 'uses' => 'Frontend\HomepageController@author'])->where('slug', '[\w\d\-\_]+');
Route::get('search', ['as' => 'frontend.search', 'uses' => 'Frontend\HomepageController@search']);
Route::get('blog/{slug}', ['as' => 'frontend.articles.show', 'uses' => 'Frontend\ArticleController@show'])->where('slug', '[\w\d\-\_]+');

Route::get('autocomplete', 'Frontend\HomepageController@autocomplete');

Route::post("favourites", 'Frontend\ArticleController@favourites')->middleware('auth');

/*
|--------------------------------------------------------------------------
| Back-end routes
|--------------------------------------------------------------------------
 */

Route::group(['prefix' => 'filemanager', 'middleware' => 'role:editor'], function () {
    Route::get('show', 'FilemanagerLaravelController@getShow');
    Route::get('connectors', 'FilemanagerLaravelController@getConnectors');
    Route::post('connectors', 'FilemanagerLaravelController@postConnectors');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'dashboard'], function () {

    //auth only
    Route::get('/', ['as' => 'backend.dashboard', 'uses' => 'Backend\DashboardController@index']);
    Route::get('profile', ['as' => 'backend.profile', 'uses' => 'Backend\ProfileController@edit']);
    Route::put('profile', 'Backend\ProfileController@update');

    Route::get('favourite-articles', ['as' => 'articles.favourites', 'uses' => 'Backend\ArticleController@favouriteArticles']);

    Route::get('avatar', ['as' => 'backend.avatar', 'uses' => 'Backend\AvatarController@edit']);
    Route::post('avatar', 'Backend\AvatarController@update');

    //admin only
    Route::group(['middleware' => 'role:admin'], function () {
        Route::resource('users', 'Backend\UserController');

        Route::get('tools', ['as' => 'backend.tools', 'uses' => 'Backend\ToolsController@index']);
        Route::post('clear-cache', 'Backend\ToolsController@clearCache');
        Route::post('maintenance-mode', 'Backend\ToolsController@maintenanceMode');
        Route::post('reset-search-index', 'Backend\ToolsController@resetIndex');

        Route::get('impersonate/{id}', 'Backend\ImpersonificationController@impersonate');
        Route::get('settings', ['as' => 'backend.settings', 'uses' => 'Backend\SettingsController@index']);
        Route::post('settings/update', 'Backend\SettingsController@update');
    });

    //admin and editor
    Route::group(['middleware' => 'role:editor'], function () {
        Route::resource('categories', 'Backend\CategoryController');
        Route::resource('tags', 'Backend\TagController');
        Route::resource('articles', 'Backend\ArticleController');
        Route::get('manager', 'Backend\MediaController@manager');
        Route::get('preview/{id}', 'Backend\ArticleController@preview');
    });

    Route::get('back-to-admin-mode', 'Backend\ImpersonificationController@backToAdminMode');
    Route::get('subscriptions', ['as' => 'backend.subscriptions', 'uses' => 'Backend\SubscriptionController@index']);

    Route::get('media', ['as' => 'backend.media', 'uses' => 'Backend\MediaController@index']);
});

app/Models/Article.php
<?php

namespace App\Models;

use App\Services\ParsedownService;
use Auth;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Article extends Model
{

    protected $table = 'blog_articles';
    protected $primaryKey = 'id';
    // protected $guarded = [];


    use Searchable;
    public function searchableAs()
    {
        return 'articles_index';
    }

    protected static function boot()
    {
        parent::boot();

        if (config('blogger.search_engine.enabled') && !app()->runningUnitTests()) {
            static::created(function ($article) {
                if ($article->is_published === 1 && ($this->published_at < Carbon::now())) {
                    $article->searchable();
                } else {
                    $article->unsearchable();
                }
            });

            static::updated(function ($article) {
                if ($article->is_published === 1 && ($article->published_at < Carbon::now())) {
                    $article->searchable();
                } else {
                    $article->unsearchable();
                }
            });
        }
    }

    public function toSearchableArray()
    {
        if ($this->is_published === 1 && $this->published_at < Carbon::now()) {
            return $this->toArray();
        }

        return [];
    }

    public function fans()
    {
        return $this->belongsToMany(User::class, 'blog_favourites');
    }

    public function isFavourite()
    {
        return $this->fans()->get()->contains(Auth::user()->id);
    }

    protected $guarded = [];

    protected $dates = ['published_at'];

    protected $append = ['author_name'];

    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Models\Tag', 'blog_articles_tags', 'article_id', 'tag_id');
    }

    public function scopePublished($query)
    {
        return $query->where('is_published', 1)->whereNotNull("published_at")->where('published_at', '<', Carbon::now());
    }

    public function updateTags($commaDelimittedTags)
    {
        $tags = explode(',', $commaDelimittedTags);
        $this->tags()->sync($tags);
    }

    public function setContentAttribute($value)
    {
        $this->attributes['content'] = $value;
        $this->attributes['html_content'] = ParsedownService::toHTML($value);
    }

    public function getAssociatedTagsAttribute()
    {
        return $this->tags->map(function ($tag) {
            return $tag->id;
        })->implode(',');
    }

    public function getReadingTimeAttribute()
    {
        $words = str_word_count(strip_tags($this->attributes['content']));
        $min = ceil($words / 200);
        return $min . ' min read';
    }

    public function author()
    {
        return $this->belongsTo('App\Models\User', 'author_id');
    }

    public function setPublishedAtAttribute($value)
    {
        $this->attributes['published_at'] = Carbon::parse($value)->format('Y-m-d H:i:00');
    }

    public function getAuthorNameAttribute()
    {
        $result = isset($this->author->display_name) ? $this->author->display_name : $this->author->email;
        return $result;
        // return ($this->author->display_name) ?? $this->author->email;
    }

    public function getCategoryNameAttribute()
    {
        return $this->category->name;
    }

}

app/Http/Controllers/Backend/ArticleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Article\ArticleCreateRequest;
use App\Http\Requests\Article\ArticleUpdateRequest;
use App\Models\Article;
use App\Models\Category;
use App\Models\Tag;
use App\Models\User;
use App\Traits\RelatedArticles;
use Auth;
use View;
use DB;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Input;

class ArticleController extends Controller
{
    use RelatedArticles;

    public function index()
    {
        $articles = Article::with('tags', 'author')->orderBy('created_at')->get();

        return View::make('backend.articles.index', compact('articles'));
    }

    public function show($id)
    {
        return redirect()->action('Backend\ArticleController@edit', $id);
    }

    public function edit($id)
    {
        $users = User::all();

        $tags = Tag::all();
  
        $categories = Category::all();

        $article = Article::with('tags', 'author', 'category')->findOrFail($id);

        return View::make('backend.articles.edit', compact('article', 'users', 'categories', 'tags'));
    }

    public function create()
    {
        $users = User::all();

        $tags = Tag::all();

        $categories = Category::all();

        return View::make('backend.articles.edit', compact('users', 'categories', 'tags'));
    }

    public function store(ArticleCreateRequest $request)
    {
        // dd($request->all());
        $article = Article::create($request->getValidRequest());
        // dd($article->id);
        $article->fresh()->updateTags($request->tags);

        if (\Input::hasFile('article_image')) {
            $data['article_image'] = time() . '.' . $request->article_image->getClientOriginalExtension();
            $destinationPath    = public_path('filemanager/userfiles');   
            $request->article_image->move($destinationPath, $data['article_image']);    
        }
        \DB::table('blog_articles')->where('id',$article->id)->update(['article_image' => $data['article_image'] ]);

        return redirect('dashboard/articles')->with('status', 'Article has been created');
    }

    public function update(ArticleUpdateRequest $request, $id)
    {
        // dd($request->all());
        $article = Article::findOrFail($id);

        $result = $article->update($request->getValidRequest());
        // dd($request->tags);
        if(!empty($request->tags)){
            $re = $article->fresh()->updateTags($request->tags);
        }
        
        // dd($re);
        if (\Input::hasFile('article_image')) {
            $data['article_image'] = time() . '.' . $request->article_image->getClientOriginalExtension();
            $destinationPath    = public_path('filemanager/userfiles');   
            $request->article_image->move($destinationPath, $data['article_image']); 
            \DB::table('blog_articles')->where('id',$id)->update(['article_image' => $data['article_image'] ]);   
        }
        // dd("oka");
        
        // dd("oka");

        return redirect()->back()->with('status', 'Article has been updated');
    }

    public function destroy($id)
    {
        Article::findOrFail($id)->delete($id);

        return redirect()->back()->with('status', 'Article has been deleted');
    }

    public function favouriteArticles()
    {
        $articles = Auth::user()->favourites;

        return view('backend.articles.favourites', compact('articles'));
    }

    public function preview($id)
    {
        $article = Article::with('tags', 'author', 'category')->findOrFail($id);

        $relatedArticles = ($this->getRelatedArticles($article)->count() > 3) ? $this->getRelatedArticles($article)->random(3) : $this->getRelatedArticles($article);

        return View::make('frontend.articles.show', compact('article', 'relatedArticles'));

    }
}

app/Http/Controllers/Backend/AvatarController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Traits\UploadAvatar;
use Auth;
use Illuminate\Http\Request;
use View;

use DB;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Input;

class AvatarController extends Controller
{

    use UploadAvatar;

    public function edit()
    {
        $user = Auth::user();

        return View::make('backend.avatar.edit', compact('user'));
    }

    public function update(Request $request)
    {
        $this->getFileContent($request->input('encodedData'));

        $this->getFileExtension();

        if ($this->isValidImage() !== true) {
            return response()->json(["success" => false, "error" => "File is not a valid image"], 422);
        }

        $this->saveAvatarForUser();

        return response()->json(["success" => true]);
    }


    public function update_avatar(Request $request,$id){
        if (\Input::hasFile('avatar')) { 
            $data['avatar'] = time() . '.' . $request->avatar->getClientOriginalExtension();
            $destinationPath    = public_path('images/avatars');   
            $request->avatar->move($destinationPath, $data['avatar']); 

             \DB::table('blog_users')->where('id',$id)->update(['avatar' => $data['avatar'] ]);   
        }
       

        return back();
    }


    


}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Category\CategoryCreateRequest;
use App\Http\Requests\Category\CategoryUpdateRequest;
use App\Models\Category;
use View;

class CategoryController extends Controller
{

    public function index()
    {
        $categories = Category::all();

        return View::make('backend.categories.index', compact('categories'));
    }

    public function show($id)
    {
        return redirect()->action('Backend\CategoryController@edit', $id);
    }

    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return View::make('backend.categories.edit', compact('category'));
    }

    public function create()
    {
        return View::make('backend.categories.edit');
    }

    public function store(CategoryCreateRequest $request)
    {
        $category = Category::create($request->getValidRequest());

        return redirect('dashboard/categories')->with('status', 'New category has been created');
    }

    public function update(CategoryUpdateRequest $request, $id)
    {

        $category = Category::findOrFail($id)->update($request->getValidRequest());

        return redirect()->back()->with('status', 'Category has been updated');
    }

    public function destroy($id)
    {
        Category::findOrFail($id)->delete($id);

        return redirect()->back()->with('status', 'Category has been deleted');
    }
}

app/Http/Controllers/Backend/ImpersonificationController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;
use Auth;
use Session;

class ImpersonificationController extends Controller
{

    public function impersonate($id)
    {
        $user = User::findOrFail($id);

        if (!$user) {
            redirect()->back();
        }

        Session::put(config('blogger.auth.impersonification.session_name'), Auth::user()->id);

        Auth::login($user, true);

        return redirect()->to('/dashboard');
    }

    public function backToAdminMode()
    {

        $adminId = config('blogger.auth.impersonification.session_name');

        if (Session::has($adminId)) {

            $user = User::findOrFail(Session::get($adminId));

            Session::remove($adminId);

            Auth::logout();

            Auth::login($user, true);

        }
        return redirect()->to('/dashboard');
    }
}

app/Http/Controllers/Backend/MediaController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use View;

class MediaController extends Controller
{

    public function index()
    {
        return View::make('backend.media.index');
    }

}

resources/views/backend/articles/edit.blade.php
@extends('layouts.backend')

@section('title')
  @if(!empty($article))
    Article - Edit
  @else
    Article - Create
  @endif
@stop

@section('content')

<div class="ui segment large">
@if(!empty($article))
  {!! Breadcrumbs::render('backend.articles.edit',$article) !!}
@else
  {!! Breadcrumbs::render('backend.articles.create') !!}
@endif
</div><!--end of segment-->

<div class="ui segment teal padded">
@if(!empty($article))
<h2>Update an Article
  &nbsp;
  <a class="ui right floated tiny primary labeled icon button" href="{{url('dashboard/preview/'.$article->id)}}">
      <i class="eye icon"></i> Preview Article
  </a>
</h2>
<form class="ui form" method="POST" action="{{url('dashboard/articles/'.$article->id)}}" enctype="multipart/form-data">
{{method_field('PUT')}}
@else
<h2>Create an Article</h2>
<form class="ui form" method="POST" action="{{url('dashboard/articles')}}" enctype="multipart/form-data">
@endif
  {{csrf_field()}}
  @include('partials._errors')
  @include('partials._success',['flashSuccess'=>'status'])

  <div class="field fluid {{ $errors->has('title') ? 'error' : '' }}">
    <label for="article-title">Title</label>
    <div class="ui input">
      <input type="text" name="title" id="article-title" placeholder="Title" value="{{  ($article->title) ?? old('title') }}" >
    </div>
  </div>

  <div class="field fluid {{ $errors->has('subtitle') ? 'error' : '' }}">
    <label for="article-subtitle">Subtitle</label>
    <div class="ui input">
      <input type="text" name="subtitle" id="article-subtitle" placeholder="Subtitle" value="{{  ($article->subtitle) ?? old('subtitle') }}" >
    </div>
  </div>

  <div class="field fluid {{ $errors->has('slug') ? 'error' : '' }}">
    <label for="article-slug">Slug</label>
    <div class="ui input">
      <input type="text" name="slug" id="article-slug" placeholder="Slug" value="{{ ($article->slug) ?? old('slug') }}" >
    </div>
  </div>

  <div class="field fluid {{ $errors->has('category') ? 'error' : '' }}">
    <label>Category</label>
    <select class="ui dropdown" name="category" value="{{ old('category')}}">
      <option value="">Category</option>
      @if(isset($categories))
        @foreach($categories as $category)
          @if(!empty($article) && $article->category->id == $category->id || old('category') == $category->id)
                <option value="{{ $category->id }}" selected="selected" >{{$category->name}} </option>
          @else
                <option value="{{ $category->id }}">{{$category->name}} </option>
          @endif
        @endforeach
      @endif
    </select>
  </div>

  <div class="field fluid {{ $errors->has('author_id') ? 'error' : '' }}">
    <label for="author_id">Author</label>
    <select class="ui dropdown" name="author_id" id="author_id" value="{{ old('author_id')}}">
      <option value="">Author</option>
      @if(isset($categories))
        @foreach($users as $user)
          @if(!empty($article) && $article->author_id == $user->id || old('author_id') == $user->id || $user->id == Auth::user()->id)
            <option value="{{ $user->id }}" selected>{{ ($user->display_name) ?? $user->email}} </option>
          @else
            <option value="{{ $user->id }}">{{ ($user->display_name) ?? $user->email}}</option>
          @endif
        @endforeach
      @endif
    </select>
  </div>

   <div class="field fluid {{ $errors->has('tags') ? 'error' : '' }}">
     <label for="tags">Tags</label>

     <select class="ui dropdown" name="tags" value="{{ old('tags')}}">
      <option value="">Tags</option>
      @if(isset($tags))
        @foreach($tags as $tag)
          @if(!empty($article) && $article->category->id == $tag->id || old('tags') == $category->id)
                <option value="{{ $tag->id }}" selected="selected" >{{$tag->name}} </option>
          @else
                <option value="{{ $tag->id }}">{{$tag->name}} </option>
          @endif
        @endforeach
      @endif
    </select>

    {{--  <div class="ui multiple selection dropdown multiple-dropdown field-prevent-send">
        <input type="hidden" name="tags" id="tags" value="{{ ($article->associated_tags) ?? old('tags') }}">
         <div class="default text">Tags</div>
         <div class="menu">
          @if(isset($tags) && count($tags))
            @foreach($tags as $tag)
              <div class="item" data-value="{{$tag->id}}">{{$tag->name}}</div>
            @endforeach
          @endif
         </div>
     </div> --}}
   </div>

     <div class="field fluid">
    <label for="article-slug">Article Image </label>
    <div class="ui input">
      <input type="file" name="article_image"  placeholder="Image">
    </div>
  </div>

   <div class="field">
     <label for="article-image">Article Image</label>
     <div class="ui left action input">
      <button class="ui teal labeled icon button" id="article-pick-image">
        <i class="image icon"></i>
        Pick Image
      </button>
      <input type="text" name="article_image" id="article-image-path" value="{{($article->article_image) ?? old('article_image') }}" placeholder="relative image url">
    </div>

   <div class="ui segment left floated segment-margin">
     <div class="ui medium bordered image">
        <img id="article-image-preview" src="{{ (isset($article) && $article->article_image)? url(config('blogger.filemanager.upload_path').'/'.$article->article_image): "" }}">
      </div>
     </div>
   </div>




  <div class="field {{ $errors->has('content') ? 'error' : '' }}">
    <label for="article-content">Content</label>
    <textarea id="my-editor" name="content" class="form-control">{!! ($article->content) ?? old('content') !!}</textarea>



    {{-- <textarea id="article-content" name="content">{{ ($article->content) ?? old('content') }}</textarea> --}}
  </div>

    <div class="field fluid {{ $errors->has('meta_description') ? 'error' : '' }}">
    <label for="meta_description">Meta Description</label>
    <div class="ui input">
      <input type="text" name="meta_description" id="meta_description" placeholder="Meta Description" value="{{($article->meta_description) ?? old('meta_description') }}" >
    </div>
  </div>

   <div class="field fluid {{ $errors->has('meta_keywords') ? 'error' : '' }}">
     <label for="meta_keywords">Meta Keywords</label>
     <div class="ui multiple search selection dropdown multiple-dropdown field-prevent-send">
        <input type="hidden" name="meta_keywords" value="{{ ($article->meta_keywords) ?? old('meta_keywords') }}">
         <div class="default text">Meta Keywords</div>
         <div class="menu"></div>
     </div>
   </div>
 

  <div class="field">
  <label for="is_published">Is published</label>
    <div class="ui left floated compact segment segment-margin">
      <div class="ui fitted toggle checkbox">
        <input type="checkbox" name="is_published" value="1" {{ (isset($article) && $article->is_published === 1 || old('is_published')) ? 'checked' : '' }}>
      </div>
   </div>
  </div>

  <div class="field fluid {{ $errors->has('published_at') ? 'error' : '' }}">
    <label for="published_at">Published at</label>
    <div class="ui input">
      <input type="text" name="published_at" class="published-at" id="published_at" placeholder="YYYY-MM-DD H:i:s" value="{{ ($article->published_at) ?? old('published_at') }}" >
    </div>
  </div>


    <button class="ui fluid fluid primary submit button" type="submit" name="submit">
    @if(!empty($article))
      Update
    @else
      Create
    @endif
    Article
   </button>
</form>
</div><!--end of segment-->

@endsection

@section('scripts')

<script>
CKEDITOR.replace('my-editor', options);
</script>

   @include('partials._filemanager_scripts')
@stop

resources/views/backend/articles/favourites.blade.php
@extends('layouts.backend')

@section('title', 'Favourite Articles')

@section('content')
<div class="ui segment large">
  {!! Breadcrumbs::render('backend.articles.favourites') !!}
</div><!--end of segment-->

<div class="ui segment teal padded">
<h2>Favourite Articles</h2>

@if($articles && count($articles)>0)
  <div class="ui relaxed divided list">
	<div class="ui divided items">
	@foreach($articles as $article)

		  <div class="item">
		    <div class="ui tiny image">
		        <a href="{{url('/blog/'.$article->slug)}}">
		          <img class="ui hoverable tiny image" src="{{(!empty($article->article_image))? url(config('blogger.filemanager.upload_path').'/'.$article->article_image): url('images/placeholder_640x480.png')}}">
		        </a>
		    </div>
		    <div class="middle aligned content">
	            <a class="header" href="{{url('/blog/'.$article->slug)}}"><h3>{{ $article->title }} </h3></a>
	            <div class="description"><a href="{{url('about/'.$article->author->slug)}}">{{ $article->author_name }}</a> <span class=" item-mute">| {{$article->published_at->diffForHumans()}}</span></div>
	        </div>
		    <div class="middle aligned content right floated">
				<a class="ui right floated tiny primary icon button no-wrap"  href="{{url('/blog/'.$article->slug)}}">
		            <i class="eye icon"></i> Read article
		    	 </a>
			</div>
		  </div>

	@endforeach
	</div>
	</div>
@else
	<div class="ui message yellow">You don't have any favourite articles yet</div>
@endif
</div>
@endsection

resources/views/backend/articles/index.blade.php
@extends('layouts.backend')

@section('title', 'Articles')

@section('content')
<div class="ui segment large">
  {!! Breadcrumbs::render('backend.articles.index') !!}
</div><!--end of segment-->

<div class="ui segment teal padded">
@include('partials._success',['flashSuccess'=>'status'])
<h2>Articles
  &nbsp;
  <a class="ui right floated tiny primary labeled icon button" href="{{url('dashboard/articles/create')}}">
      <i class="plus add icon"></i> Add New Article
  </a>
</h2>



<div id="article-table-list">
<div class="ui left icon input table-list-search-input">
  <input type="text" class="search" placeholder="Search articles..." id="article-list-search">
   <i class="file text outline icon"></i>
</div>
<div class="list-pagination top-list-pagination"></div>
  <table  class="ui celled table" cellspacing="0" width="100%">
    <thead>
          <tr class="text-center">
              <th class="sortable" data-sort="article-table-id"> Id <i class="sort icon"></i></th>
              <th class="sortable" data-sort="article-table-title">Title <i class="sort icon"></i></th>
              <th class="sortable" data-sort="article-table-category-name">Category <i class="sort icon"></i></th>
              <th class="sortable" data-sort="article-table-author-name">Author <i class="sort icon"></i></th>
              <th class="sortable" data-sort="article-table-status">Status <i class="sort icon"></i></th>
              <th class="sortable" data-sort="article-table-created-at">Created at <i class="sort icon"></i></th>
              <th>Actions</th>
          </tr>
      </thead>
      <tbody class="listable text-center">
      @if(isset($articles) && count($articles))
        @foreach($articles as $article)
          <tr>
            <td class="article-table-id">{{$article->id}}</td>
            <td class="article-table-title">{{ str_limit($article->title, $limit = 50, $end = '...') }}</td>
             <td class="article-table-category-name">{{$article->category_name}}</td>
            <td class="article-table-author-name">{{$article->author_name}}</td>
            <td class="article-table-status">
              @if($article->is_published && $article->published_at !== null &&  $article->published_at < Carbon\Carbon::now())
               <span class="ui label green">Published</span>
              @else
                <span class="ui label grey">Draft</span>
              @endif
            </td>
            <td class="article-table-created-at">{{$article->created_at->format('d M Y')}}</td>
            <td>
              <a href="{{url('dashboard/articles/'.$article->id.'/edit')}}" id="edit-article-{{$article->id}}"  class="mini ui button primary"><i class="edit icon"></i> Edit</a>
              @if(Auth::user()->hasRole('admin'))
              <form class="form-inline form-delete-article" method="POST" action="/dashboard/articles/{{$article->id}}">
                {{csrf_field()}}
                 <input name="_method" type="hidden" value="DELETE">
                 <button class="ui mini button red" id="delete-article-{{$article->id}}" type="submit"><i class="icon remove article"></i> Delete</button>

              </form>
              @endif
            </td>
          </tr>

        @endforeach

    @endif
          <tr id="article-table-no-results" style="display:none;"><td colspan="7">No results</td></tr>
      </tbody>

  </table>
<div class="list-pagination bottom-list-pagination"></div>
</div>

</div>

@endsection