routes/web.php
<?php

Route::get('encrypts',function(){
    dd(bcrypt('admin'));
});

//Clear configurations:
            Route::get('/config-clear', function() {
                $status = Artisan::call('config:clear');
                return '<h1>Configurations cleared</h1>';
            });

//Clear cache:
            Route::get('/cache-clear', function() {
                $status = Artisan::call('cache:clear');
                return '<h1>Cache cleared</h1>';
            });

//Clear configuration cache:
            Route::get('/config-cache', function() {
                $status = Artisan::call('config:cache');
                return '<h1>Configurations cache cleared</h1>';
            });
    Route::get('/reset', function(){
        \Artisan::call('migrate:refresh',['--seed' => ' ']);
    });
/*
|--------------------------------------------------------------------------
| Auth routes
|--------------------------------------------------------------------------
 */

//Authentication routes
Route::auth();
Route::get('logout', 'Auth\LoginController@logout');
Route::get('password/reset/{token}/{email}', 'Auth\ResetPasswordController@showResetForm');

//OAuth2 routes
Route::get('auth/facebook', 'OAuth\FacebookController@login');
Route::get('auth/facebook/callback', "OAuth\FacebookController@callback");

Route::get('auth/twitter', 'OAuth\TwitterController@login');
Route::get('auth/twitter/callback', "OAuth\TwitterController@callback");

Route::get('auth/google', 'OAuth\GoogleController@login');
Route::get('auth/google/callback', "OAuth\GoogleController@callback");
Route::post('upload_avatar/{id}','Backend\AvatarController@update_avatar');
/*
|--------------------------------------------------------------------------
| Front-end routes
|--------------------------------------------------------------------------
 */

Route::get("/", ['as' => 'home', 'uses' => 'Frontend\ArticleController@index']);

Route::get("sitemap", ['as' => 'frontend.sitemap', 'uses' => 'Frontend\HomepageController@sitemap']);
Route::get("terms-and-conditions", ['as' => 'frontend.terms-and-conditions', 'uses' => 'Frontend\HomepageController@termsAndConditions']);
Route::get("privacy-policy", ['as' => 'frontend.privacy-policy', 'uses' => 'Frontend\HomepageController@privacyPolicy']);

Route::post('subscribe', 'Frontend\HomepageController@subscribe');
Route::get('subscription/confirm/{email}', ['as' => 'frontend.subscription', 'uses' => 'Frontend\HomepageController@subscriptionConfirm']);

Route::get("categories", ['as' => 'frontend.categories', 'uses' => 'Frontend\CategoryController@index']);
Route::get("categories/{slug}", ['as' => 'frontend.categories.show', 'uses' => 'Frontend\CategoryController@show'])->where('slug', '[\w\d\-\_]+');

Route::get("tags", ['as' => 'frontend.tags', 'uses' => 'Frontend\TagController@index']);
Route::get("tags/{slug}", ['as' => 'frontend.tags.show', 'uses' => 'Frontend\TagController@show'])->where('slug', '[\w\d\-\_]+');

Route::post('contact', 'Frontend\HomepageController@contact');
Route::get('about', ['as' => 'frontend.about', 'uses' => 'Frontend\HomepageController@about']);
Route::get('about/{slug}', ['as' => 'frontend.about.author', 'uses' => 'Frontend\HomepageController@author'])->where('slug', '[\w\d\-\_]+');
Route::get('search', ['as' => 'frontend.search', 'uses' => 'Frontend\HomepageController@search']);
Route::get('blog/{slug}', ['as' => 'frontend.articles.show', 'uses' => 'Frontend\ArticleController@show'])->where('slug', '[\w\d\-\_]+');

Route::get('autocomplete', 'Frontend\HomepageController@autocomplete');

Route::post("favourites", 'Frontend\ArticleController@favourites')->middleware('auth');

/*
|--------------------------------------------------------------------------
| Back-end routes
|--------------------------------------------------------------------------
 */

Route::group(['prefix' => 'filemanager', 'middleware' => 'role:editor'], function () {
    Route::get('show', 'FilemanagerLaravelController@getShow');
    Route::get('connectors', 'FilemanagerLaravelController@getConnectors');
    Route::post('connectors', 'FilemanagerLaravelController@postConnectors');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'dashboard'], function () {

    //auth only
    Route::get('/', ['as' => 'backend.dashboard', 'uses' => 'Backend\DashboardController@index']);
    Route::get('profile', ['as' => 'backend.profile', 'uses' => 'Backend\ProfileController@edit']);
    Route::put('profile', 'Backend\ProfileController@update');

    Route::get('favourite-articles', ['as' => 'articles.favourites', 'uses' => 'Backend\ArticleController@favouriteArticles']);

    Route::get('avatar', ['as' => 'backend.avatar', 'uses' => 'Backend\AvatarController@edit']);
    Route::post('avatar', 'Backend\AvatarController@update');

    //admin only
    Route::group(['middleware' => 'role:admin'], function () {
        Route::resource('users', 'Backend\UserController');

        Route::get('tools', ['as' => 'backend.tools', 'uses' => 'Backend\ToolsController@index']);
        Route::post('clear-cache', 'Backend\ToolsController@clearCache');
        Route::post('maintenance-mode', 'Backend\ToolsController@maintenanceMode');
        Route::post('reset-search-index', 'Backend\ToolsController@resetIndex');

        Route::get('impersonate/{id}', 'Backend\ImpersonificationController@impersonate');
        Route::get('settings', ['as' => 'backend.settings', 'uses' => 'Backend\SettingsController@index']);
        Route::post('settings/update', 'Backend\SettingsController@update');
    });

    //admin and editor
    Route::group(['middleware' => 'role:editor'], function () {
        Route::resource('categories', 'Backend\CategoryController');
        Route::resource('tags', 'Backend\TagController');
        Route::resource('articles', 'Backend\ArticleController');
        Route::get('manager', 'Backend\MediaController@manager');
        Route::get('preview/{id}', 'Backend\ArticleController@preview');
    });

    Route::get('back-to-admin-mode', 'Backend\ImpersonificationController@backToAdminMode');
    Route::get('subscriptions', ['as' => 'backend.subscriptions', 'uses' => 'Backend\SubscriptionController@index']);

    Route::get('media', ['as' => 'backend.media', 'uses' => 'Backend\MediaController@index']);
});

app/Models/Article.php
<?php

namespace App\Models;

use App\Services\ParsedownService;
use Auth;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Article extends Model
{

    protected $table = 'blog_articles';
    protected $primaryKey = 'id';
    // protected $guarded = [];


    use Searchable;
    public function searchableAs()
    {
        return 'articles_index';
    }

    protected static function boot()
    {
        parent::boot();

        if (config('blogger.search_engine.enabled') && !app()->runningUnitTests()) {
            static::created(function ($article) {
                if ($article->is_published === 1 && ($this->published_at < Carbon::now())) {
                    $article->searchable();
                } else {
                    $article->unsearchable();
                }
            });

            static::updated(function ($article) {
                if ($article->is_published === 1 && ($article->published_at < Carbon::now())) {
                    $article->searchable();
                } else {
                    $article->unsearchable();
                }
            });
        }
    }

    public function toSearchableArray()
    {
        if ($this->is_published === 1 && $this->published_at < Carbon::now()) {
            return $this->toArray();
        }

        return [];
    }

    public function fans()
    {
        return $this->belongsToMany(User::class, 'blog_favourites');
    }

    public function isFavourite()
    {
        return $this->fans()->get()->contains(Auth::user()->id);
    }

    protected $guarded = [];

    protected $dates = ['published_at'];

    protected $append = ['author_name'];

    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Models\Tag', 'blog_articles_tags', 'article_id', 'tag_id');
    }

    public function scopePublished($query)
    {
        return $query->where('is_published', 1)->whereNotNull("published_at")->where('published_at', '<', Carbon::now());
    }

    public function updateTags($commaDelimittedTags)
    {
        $tags = explode(',', $commaDelimittedTags);
        $this->tags()->sync($tags);
    }

    public function setContentAttribute($value)
    {
        $this->attributes['content'] = $value;
        $this->attributes['html_content'] = ParsedownService::toHTML($value);
    }

    public function getAssociatedTagsAttribute()
    {
        return $this->tags->map(function ($tag) {
            return $tag->id;
        })->implode(',');
    }

    public function getReadingTimeAttribute()
    {
        $words = str_word_count(strip_tags($this->attributes['content']));
        $min = ceil($words / 200);
        return $min . ' min read';
    }

    public function author()
    {
        return $this->belongsTo('App\Models\User', 'author_id');
    }

    public function setPublishedAtAttribute($value)
    {
        $this->attributes['published_at'] = Carbon::parse($value)->format('Y-m-d H:i:00');
    }

    public function getAuthorNameAttribute()
    {
        $result = isset($this->author->display_name) ? $this->author->display_name : $this->author->email;
        return $result;
        // return ($this->author->display_name) ?? $this->author->email;
    }

    public function getCategoryNameAttribute()
    {
        return $this->category->name;
    }

}

app/Http/Controllers/Backend/ArticleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Article\ArticleCreateRequest;
use App\Http\Requests\Article\ArticleUpdateRequest;
use App\Models\Article;
use App\Models\Category;
use App\Models\Tag;
use App\Models\User;
use App\Traits\RelatedArticles;
use Auth;
use View;
use DB;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Input;

class ArticleController extends Controller
{
    use RelatedArticles;

    public function index()
    {
        $articles = Article::with('tags', 'author')->orderBy('created_at')->get();

        return View::make('backend.articles.index', compact('articles'));
    }

    public function show($id)
    {
        return redirect()->action('Backend\ArticleController@edit', $id);
    }

    public function edit($id)
    {
        $users = User::all();

        $tags = Tag::all();
  
        $categories = Category::all();

        $article = Article::with('tags', 'author', 'category')->findOrFail($id);

        return View::make('backend.articles.edit', compact('article', 'users', 'categories', 'tags'));
    }

    public function create()
    {
        $users = User::all();

        $tags = Tag::all();

        $categories = Category::all();

        return View::make('backend.articles.edit', compact('users', 'categories', 'tags'));
    }

    public function store(ArticleCreateRequest $request)
    {
        // dd($request->all());
        $article = Article::create($request->getValidRequest());
        // dd($article->id);
        $article->fresh()->updateTags($request->tags);

        if (\Input::hasFile('article_image')) {
            $data['article_image'] = time() . '.' . $request->article_image->getClientOriginalExtension();
            $destinationPath    = public_path('filemanager/userfiles');   
            $request->article_image->move($destinationPath, $data['article_image']);    
        }
        \DB::table('blog_articles')->where('id',$article->id)->update(['article_image' => $data['article_image'] ]);

        return redirect('dashboard/articles')->with('status', 'Article has been created');
    }

    public function update(ArticleUpdateRequest $request, $id)
    {
        // dd($request->all());
        $article = Article::findOrFail($id);

        $result = $article->update($request->getValidRequest());
        // dd($request->tags);
        if(!empty($request->tags)){
            $re = $article->fresh()->updateTags($request->tags);
        }
        
        // dd($re);
        if (\Input::hasFile('article_image')) {
            $data['article_image'] = time() . '.' . $request->article_image->getClientOriginalExtension();
            $destinationPath    = public_path('filemanager/userfiles');   
            $request->article_image->move($destinationPath, $data['article_image']); 
            \DB::table('blog_articles')->where('id',$id)->update(['article_image' => $data['article_image'] ]);   
        }
        // dd("oka");
        
        // dd("oka");

        return redirect()->back()->with('status', 'Article has been updated');
    }

    public function destroy($id)
    {
        Article::findOrFail($id)->delete($id);

        return redirect()->back()->with('status', 'Article has been deleted');
    }

    public function favouriteArticles()
    {
        $articles = Auth::user()->favourites;

        return view('backend.articles.favourites', compact('articles'));
    }

    public function preview($id)
    {
        $article = Article::with('tags', 'author', 'category')->findOrFail($id);

        $relatedArticles = ($this->getRelatedArticles($article)->count() > 3) ? $this->getRelatedArticles($article)->random(3) : $this->getRelatedArticles($article);

        return View::make('frontend.articles.show', compact('article', 'relatedArticles'));

    }
}

app/Http/Controllers/Frontend/ArticleController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Traits\RelatedArticles;
use Auth;
use Illuminate\Http\Request;

class ArticleController extends Controller
{

    use RelatedArticles;

    public function index()
    {
        $articles = Article::published()->paginate(config('blogger.articles_per_page'));

        return view('frontend.articles.index', compact('articles'));
    }

    public function show($slug)
    {
        $article = Article::where('slug', $slug)->firstOrFail();

        $relatedArticles = (count($this->getRelatedArticles($article)) > 3) ? $this->getRelatedArticles($article)->random(3) : $this->getRelatedArticles($article);

        return view('frontend.articles.show', compact('article', 'relatedArticles'));
    }

    public function favourites(Request $request)
    {
        $article = Article::findOrFail($request->input('id'));

        $user = Auth::user()->favourites()->toggle($article->id);

        return response()->json(['success' => true]);
    }

}

app/Http/Controllers/Frontend/CategoryController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Category;

class CategoryController extends Controller
{

    public function index()
    {
        $categories = Category::all()->sort(function ($previousCategory, $nextCategory) {
            return $previousCategory->getArticlesCountAttribute() <=> $nextCategory->getArticlesCountAttribute();
        })->reverse();

        return view('frontend.categories.index', compact('categories'));
    }

    public function show($slug)
    {
        $category = Category::where('slug', $slug)->with('articles')->firstOrFail();

        return view('frontend.categories.show', compact('category'));
    }

}

app/Http/Controllers/Frontend/TagController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Tag;

class TagController extends Controller
{

    public function index()
    {
        $tags = Tag::all()->sort(function ($previousTag, $nextTag) {
            return $previousTag->getArticlesCountAttribute() <=> $nextTag->getArticlesCountAttribute();
        })->reverse();

        return view('frontend.tags.index', compact('tags'));
    }

    public function show($slug)
    {
        $tag = Tag::where('slug', $slug)->with('articles')->firstOrFail();

        return view('frontend.tags.show', compact('tag'));
    }

}

resources/views/frontend/articles/index.blade.php
<style type="text/css">
  .backend-dashboard{
    width: 100% !important;
  }
  .ui.container.narrowed{
    width: 100vw !important;
  }
  div.ui.card.blogger-card{
    width: 80% !important;
  }
  .ui.container.narrowed {
  /*max-width: 750px !important;*/
  width: 100% !important;
  margin: 0 auto !important;
}
</style>

@extends('layouts.frontend')

@section('title', 'Articles')

@section('content')
    @if(isset($articles))
      @if(config('blogger.articles_render_type') === 'single')
        @include('partials._articles_single')
      @elseif(config('blogger.articles_render_type') === 'multiple')
        @include('partials._articles_multiple')
      @else
      <div class="ui grid">
        <div class="ui grid container">
          <div class="column">
            <div class="ui message yellow">
              <p>Unsupported articles render type. Please check your config/blogger.php </p>
              <p>Supported types: "single", "multiple"</p>
            </div>
          </div>
        </div>
      </div>
      @endif
    @else
    <div class="ui grid">
      <div class="ui grid container">
        <div class="column">
          <div class="ui message yellow">
            You must migrate and seed your databases to see the articles
          </div>
        </div>
      </div>
    </div>
    @endif

@endsection

resources/views/frontend/articles/show.blade.php
@extends(config('blogger.article_layout'),[
  'meta_keywords' => $article->meta_keywords,
  'meta_description' => $article->meta_description,
])

@section('title', $article->title)

@section('og-title')
  <meta property="og:title" content="{{ $article->title }}"/>
@stop

@section('og-description')
  <meta property="og:description" content="{{ $article->meta_description }}"/>
@stop

@if(!empty($article->article_image))
    @section('og-image')
      <meta property="og:image" content="{{ url(config('blogger.filemanager.upload_path').'/'.$article->article_image) }}">
    @stop
@endif

@section('content')
<div class="ui segments raised">

  <div class="ui segment">
    {!! Breadcrumbs::render('frontend.articles.show', $article) !!}
  </div><!--end of segment-->

  <div class="ui segment teal">

      @if($article)
      <article>
        <header>
          <div class="ui divided items">

          <div class="item item-article">

            <a class="ui avatar-sm item-image" href="{{ url('about/'.$article->author->slug) }}">
                 <img class="ui avatar-sm" src="{{(!empty($article->author->avatar))? url('images/avatars/'.$article->author->avatar) : url('images/avatars/avatar_default.png')}}">
            </a>

            <div class="middle aligned content">
                  <a class="ui header item-mute" href="{{ url('about/'.$article->author->slug) }}">{{ $article->author_name }}</a>
                  <div><strong>{{ (!empty($article->author->job))? $article->author->job : "Editor" }}</strong></div>
                  <div class="item-mute"><i class="clock icon"></i>{{ $article->reading_time}} | {{ $article->published_at->diffForHumans()}}</div>

            </div>

                  @if(Auth::user() && Auth::user()->hasRole('editor'))
            <div class="middle aligned content ">
              <a class="ui right floated tiny primary icon button no-wrap"  href="{{ url('dashboard/articles/'.$article->id.'/edit') }}">
                  <i class="edit icon"></i> Edit
              </a>
            </div>
            @endif
          </div>
          </div>
            <h1 class="article-title"><a href="">{{ $article->title }}</a></h1>
        </header>

        <div class="article-content">
         <div class="ui fluid image">
                 <div class="ui teal big ribbon label z-index-top">
                    <a href="{{ url('categories/'.$article->category->slug) }}" class="white-font">{{$article->category_name}}</a>
                </div>
               {{--  @if(Auth::check())
                <a class="ui right  teal corner label favorite" href="javascript:void(0)" data-id="{{ $article->id }}" data-content="Add to favourites" data-variation="inverted">
                  <i class="{{($article->isFavourite())? 'yellow active ': 'white '}}star icon"></i>
                </a>
                @endif --}}
               <img class="ui fluid image" src="{{(!empty($article->article_image))? url(config('blogger.filemanager.upload_path').'/'.$article->article_image): url('images/placeholder_640x480.png')}}" alt="picture">
          </div>
          {!!html_entity_decode($article->html_content)!!}

        </div>

        <footer>
          <div class="article-share">
              <h4>Share:</h4>
             @include('partials._share_buttons',['article' => $article])
          </div>
          <br />
          <div class="article-tags">
            <h4>Tags:</h4>
            @foreach($article->tags as $tag)
             <a class="ui large teal label" href="{{ url('tags/'.$tag->slug) }}">{{ $tag->name }}</a>
            @endforeach
          </div>
          <br />
          @include('partials._disqus',['url'=>url('blog/'.$article->slug), 'identifier' => $article->id])
        </footer>

      </article>
      @endif


    </div><!--end of segment-->
</div><!--end of segments-->
@if($relatedArticles && count($relatedArticles) > 0)
<div class="ui segments raised center">
  <div class="ui segment">
  <h2><i class="empty heart icon"></i> Related reads</h2>
  <div class="ui relaxed grid">
      <div class="three column row stackable">
        @foreach($relatedArticles as $article)
        <div class="column text-center">
           <a href="{{url('blog/'.$article->slug)}}">
            <div class="ui card">
              <div class="content content-limit">{{str_limit($article->title, $limit = 50, $end = '...')}}</div>
              <div class="image">
                 <img class="ui image floated" src="{{(!empty($article->article_image))? url(config('blogger.filemanager.upload_path').'/'.$article->article_image): url('images/placeholder_640x480.png')}}" alt="picture" />
              </div>
              <div class="content">

                <img class="ui avatar mini image" src="{{(!empty($article->author->avatar))? url('images/avatars/'.$article->author->avatar) : url('images/avatars/avatar_default.png')}}"> {{$article->author->display_name}}
              </div>

              <div class="extra content">
                     <div class="item-mute"><i class="clock icon"></i>{{ $article->reading_time}}  |  {{ $article->published_at->diffForHumans()}}</div>
              </div>
            </div>
          </a>
        </div>
        @endforeach
      </div>
  </div>
  </div>
</div><!--end of segments-->
@endif
@endsection